CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, -- Имя пользователя
    password VARCHAR(100) NOT NULL, -- Хэш пароля
    roles VARCHAR(100) NOT NULL -- Роли (например, USER,ADMIN)
);

CREATE TABLE IF NOT EXISTS oauth2_clients (
    client_id VARCHAR(50) NOT NULL PRIMARY KEY,
    client_secret VARCHAR(100) NOT NULL, -- Секрет клиента
    redirect_uris VARCHAR(255), -- URI для редиректа
    scopes VARCHAR(100), -- Разрешенные скопы
    grant_types VARCHAR(100) -- Разрешенные типы грантов
);

CREATE INDEX idx_users_username ON users(username);