spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh