spring:
  r2dbc:
    url: r2dbc:h2:mem:///customerdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

# prod
#spring:
#  r2dbc:
#    url: r2dbc:postgresql://customer-db:5432/customer_db
#    username: user
#    password: password