eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  r2dbc:
    url: r2dbc:h2:mem:///loandb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

# prod
#spring:
#  r2dbc:
#    url: r2dbc:postgresql://loan-db:5432/loan_db
#    username: user
#    password: password